### ISSUE TITLE
No computation in setDT

### ISSUE THREAD

**Issue by jangorecki** [zappingseb/dtplyrtest#1]
Haven't went through the post, but just spotted this sentence which is wrong.

> A lot of computation time is needed to convert a data.frame into a data.table.

No computation is needed, changing class attribute cannot be considered as a computation, it doesn't even touch the data. Same is valid when converting to a list, it is not specific to data.table class.

**Comment by zappingseb** [comment]
Hm. I am not sure. It might be due to my bad English, but I found this definition as Google result1:

Definition of computation according to https://www.merriam-webster.com/dictionary/computation

1a : the act or action of computing : calculation
b : the use or operation of a computer

Where 1b would totally fit.

I will change it to "conversion", though 😄

**Comment by jangorecki** [comment]
there is no need for any conversion, changing between "list - data.frame - data.table - tibble" is just setting an attribute, it has constant time not related to size of data, because we set attribute on a pointer to data, not data itself. If you do want to make a copy of data, what `as.data.table` or similar methods do, then it is not really benchmarking of an X operation, but and X and a copy of data.

**Comment by zappingseb** [comment]
Yes, right. This is why it is outside of the benchmarking inside the plots 👍 But people sometimes do not start with their data in the right format. Most people will get it either as a `data.frame` or `tibble` from a certain read function or API they are using.

**Comment by jangorecki** [comment]
@zappingseb `as.data.table` does copy the data, and it seems to be on the first plot on the very top of the blog post.
you may find [this benchmarking tips](https://rdatatable.gitlab.io/data.table/articles/datatable-benchmarking.html) useful

**Comment by zappingseb** [comment]
I replaced the image. But reading the text should make clear that data copying or transformation did not influence the benchmarking results. 
The article does not benchmark `data.table`. It is taken as the reference in this article.
