### ISSUE TITLE
Wrong computation in test_dataset_numeric.R

### ISSUE THREAD

**Issue by stefanfritsch** [zappingseb/dtplyrtest#2]
Hi,

thanks for the nice article. There is a bug in the calculation of the number of rows however:

```
 df %>%
      filter(!is.na(missing)) %>% 
      group_by(letter) %>% 
      summarise(n = n(), delay = mean(numeric_int))
```
and

```
DT_int[, .(.N, mean(numeric_int[!is.na(missing)])), by = letter]
```

are not identical. In one you compute the number of rows including the `NA` rows and in the other without. (Unless I misunderstand dplyr :) ). This should return the same result:

```
DT_int[!is.na(missing),
       .(n = .N, delay = mean(numeric_int)),
       letter]
```

On a related note, I also don't see the reason why in `test_dataset_char.R
` the following has to be so ugly:
```
DT[letter == "A", word_new:=paste0(word, numeric_int)][letter == "A", "word_new"]
```

```
DT[letter == "A",
   .(word_new = paste0(word, numeric_int))]
```

does the same and should be faster (marginally - the second filter on `letter=="A"` operates on an indexed column and should take next to no time)

**Comment by zappingseb** [comment]
Thank you soo much. The same issue came up via Email from Dirk Raetzel (http://www.spaetzle.de/infos.html). I hope it is solved. The article will be updated within the next hour

**Comment by stefanfritsch** [comment]
Thanks!

I like the repo approach for this. It could be nice to build a repository for benchmarks and comparing dplyr and data.table syntax. I don't know if you plan something like that or if this is a one-shot, though. =)
